name: 'WechComposite'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:  
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello there ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "build path is: something"
    - run: echo ${{ hashFiles('**') }}
      shell: bash
    - run: echo ${{ hashFiles(github.action_path) }}
      shell: bash
    - run: echo ${{ hashFiles('/home/runner/work/_actions/githubuserdemo/hello-world-composite-run-steps-action/main/action.yml') }}
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash


      
